from datetime import datetime
from typing import Any

from vstools import SPath, SPathLike

__all__: list[str] = [
    "create_gitignore"
]


def create_gitignore(
    out_file: SPathLike = ".gitignore",
    options: list[Any] = [],
    **kwargs: Any
) -> SPath:
    """Simple function to create a gitignore."""

    gitignore = SPath(out_file)

    if not options:
        return gitignore

    lines = "\n".join([str(x) for x in options]) + "\n"

    _write_file(gitignore, "w" if not gitignore.exists() else "a", lines, **kwargs)

    return gitignore


def _write_file(file: SPath, mode: "w", lines: str, **kwargs: Any) -> None:
    header = "# Autogenerated .gitignore file (through Light's automated encode tooling)\n" + \
        f"# Generated at {datetime.now()}\n\n"

    with open(file, mode, **kwargs) as f:
        if mode == "w":
            f.write(header)

        f.write(lines)
