from datetime import datetime
from pathlib import Path
from typing import Any

__all__: list[str] = [
    "create_gitignore",
]


def append_gitignore(
    out_file: str = ".gitignore",
    options: list[Any] = [],
    **kwargs: Any
) -> Path:
    """Simple function to append to a gitignore and create one if it doesn't exist."""

    gitignore = Path(out_file)

    if not options:
        return gitignore

    lines = "\n".join([str(x) for x in options]) + "\n"

    _write_file(gitignore, "w" if not gitignore.exists() else "a", lines, **kwargs)

    return gitignore


def _write_file(file: Path, mode: str, lines: str, **kwargs: Any) -> None:
    header = "# Autogenerated .gitignore file (through Light's automated encode tooling)\n" + \
        f"# Generated at {datetime.now()}\n\n"

    with open(file, mode, **kwargs) as f:
        if mode == "w":
            f.write(header)

        f.write(lines)
